language: ruby
rvm:
  - 2.0.0-p353

before_script:
  - rake db:migrate
  - rake db:migrate RAILS_ENV=test

# uncomment this line if your project needs to run something other than `rake`:
#script: bundle exec rspec spec
